### **Student Information**
Name: Sanly Frenot

Student ID:M11401809

GitHub ID:Slee08-tech

Kaggle name:Sanly Frenot or slee08

Kaggle private scoreboard snapshot:

![pic_ranking.png](https://github.com/Slee08-tech/DM2025-Lab2-Exercise/blob/main/pics/pic_ranking.png?raw=1)

---

# **Instructions**

For this lab we have divided the assignments into **three phases/parts**. The `first two phases` refer to the `exercises inside the Master notebooks` of the [DM2025-Lab2-Exercise Repo](https://github.com/difersalest/DM2025-Lab2-Exercise.git). The `third phase` refers to an `internal Kaggle competition` that we are gonna run among all the Data Mining students. Together they add up to `100 points` of your grade. There are also some `bonus points` to be gained if you complete `extra exercises` in the lab **(bonus 15 pts)** and in the `Kaggle Competition report` **(bonus 5 pts)**.

**Environment recommendations to solve lab 2:**
- **Phase 1 exercises:** Need GPU for training the models explained in that part, if you don't have a GPU in your laptop it is recommended to run in Colab or Kaggle for a faster experience, although with CPU they can still be solved but with a slower execution.
- **Phase 2 exercises:** We use Gemini's API so everything can be run with only CPU without a problem.
- **Phase 3 exercises:** For the competition you will probably need GPU to train your models, so it is recommended to use Colab or Kaggle if you don't have a laptop with a dedicated GPU.
- **Optional Ollama Notebook (not graded):** You need GPU, at least 4GB of VRAM with 16 GB of RAM to run the local open-source LLM models.

## **Phase 1 (30 pts):**

1. __Main Exercises (25 pts):__ Do the **take home exercises** from Sections: `1. Data Preparation` to `9. High-dimension Visualization: t-SNE and UMAP`, in the [DM2025-Lab2-Master-Phase_1 Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_1.ipynb). Total: `8 exercises`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 3th, 11:59 pm, Monday)`**

2. **Code Comments (5 pts):** **Tidy up the code in your notebook**.

## **Phase 2 (30 pts):**

1. **Main Exercises (25 pts):** Do the remaining **take home exercises** from Section: `2. Large Language Models (LLMs)` in the [DM2025-Lab2-Master-Phase_2_Main Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Main.ipynb). Total: `5 exercises required from sections 2.1, 2.2, 2.4 and 2.6`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**

2. **Code Comments (5 pts):** **Tidy up the code in your notebook**.

3. **`Bonus (15 pts):`** Complete the bonus exercises in the [DM2025-Lab2-Master-Phase_2_Bonus Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Bonus.ipynb) and [DM2025-Lab2-Master-Phase_2_Main Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Main.ipynb) `where 2 exercises are counted as bonus from sections 2.3 and 2.5 in the main notebook`. Total: `7 exercises`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**

## **Phase 3 (40 pts):**

1. **Kaggle Competition Participation (30 pts):** Participate in the in-class **Kaggle Competition** regarding Emotion Recognition on Twitter by clicking in this link: **[Data Mining Class Kaggle Competition](https://www.kaggle.com/t/3a2df4c6d6b4417e8bf718ed648d7554)**. The scoring will be given according to your place in the Private Leaderboard ranking:
    - **Bottom 40%**: Get 20 pts of the 30 pts in this competition participation part.

    - **Top 41% - 100%**: Get (0.6N + 1 - x) / (0.6N) * 10 + 20 points, where N is the total number of participants, and x is your rank. (ie. If there are 100 participants and you rank 3rd your score will be (0.6 * 100 + 1 - 3) / (0.6 * 100) * 10 + 20 = 29.67% out of 30%.)   
    Submit your last submission **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**. Make sure to take a screenshot of your position at the end of the competition and store it as `pic_ranking.png` under the `pics` folder of this repository and rerun the cell **Student Information**.

2. **Competition Report (10 pts)** A report section to be filled in inside this notebook in Markdown Format, we already provided you with the template below. You need to describe your work developing the model for the competition. The report should include a section describing briefly the following elements:
* Your preprocessing steps.
* The feature engineering steps.
* Explanation of your model.

* **`Bonus (5 pts):`**
    * You will have to describe more detail in the previous steps.
    * Mention different things you tried.
    * Mention insights you gained.

[Markdown Guide - Basic Syntax](https://www.markdownguide.org/basic-syntax/)

**`Things to note for Phase 3:`**

* **The code used for the competition should be in this Jupyter Notebook File** `DM2025-Lab2-Homework.ipynb`.

* **Push the code used for the competition to your repository**.

* **The code should have a clear separation for the same sections of the report, preprocessing, feature engineering and model explanation. Briefly comment your code for easier understanding, we provide a template at the end of this notebook.**

* Showing the kaggle screenshot of the ranking plus the code in this notebook will ensure the validity of your participation and the report to obtain the corresponding points.

After the competition ends you will have two days more to submit the `DM2025-Lab2-Homework.ipynb` with your report in markdown format and your code. Do everything **`BEFORE the deadline (Nov. 26th, 11:59 pm, Wednesday) to obtain 100% of the available points.`**

Upload your files to your repository then submit the link to it on the corresponding NTU Cool assignment.

## **Deadlines:**

![lab2_deadlines](https://github.com/Slee08-tech/DM2025-Lab2-Exercise/blob/main/pics/lab2_deadlines.png?raw=1)

---

Next you will find the template report with some simple markdown syntax explanations, use it to structure your content.

You can delete the syntax suggestions after you use them.

---

***

# **Project Report**

**Syntax:** `#` creates the largest heading (H1).

---
**Syntax:** `---` creates a horizontal rule (a separator line).

## 1. Model Development (10 pts Required)

**Syntax:** `##` creates a secondary heading (H2).

**Describe briefly each section, you can add graphs/charts to support your explanations.**

### 1.1 Preprocessing Steps

**Syntax:** `###` creates a tertiary heading (H3).

[Content for Preprocessing]

**Example Syntax for Content:**
*   **Bold text:** `**text**`
*   *Italic text*: `*text*`
*   Bullet point list:
    * Item 1
    * Item 2

Markdown Syntax to Add Image: `![Kaggle Score](pics/pic_ranking.png)`

![Example Markdown Syntax to Add Image](https://github.com/Slee08-tech/DM2025-Lab2-Exercise/blob/main/pics/example_md_img.png?raw=1)

### 1.2 Feature Engineering Steps

[Content for Feature Engineering]

### 1.3 Explanation of Your Model

[Content for Model Explanation]

---

## 2. Bonus Section (5 pts Optional)

**Add more detail in previous sections**

### 2.1 Mention Different Things You Tried

[Content for Experiments]

### 2.2 Mention Insights You Gained

[Content for Insights]

---

**`From here on starts the code section for the competition.`**

---

In [41]:
import pandas as pd
import numpy as np
import re, string

# Load competition data
id_df = pd.read_csv("data_identification.csv")
emotion_df = pd.read_csv("emotion.csv")
posts_raw = pd.read_json("final_posts.json")

print("Loaded files successfully!")
print("ID file:", id_df.shape)
print("Emotion file:", emotion_df.shape)
print("Posts file:", posts_raw.shape)

Loaded files successfully!
ID file: (64171, 2)
Emotion file: (47890, 2)
Posts file: (64171, 1)

# **Competition Code**

## 1. Preprocessing Steps

In [36]:
### Add the code related to the preprocessing steps in cells inside this section
def extract_post_info(root_dict):
    d = root_dict


    src = d.get("_source", d)
    post = src.get("post", src)

    post_id = (
        post.get("id")
        or post.get("post_id")
        or post.get("tweet_id")
    )
    text = (
        post.get("text")
        or post.get("content")
        or post.get("body")
    )

    return pd.Series({"id": post_id, "text": text})

posts_flat = posts_raw["root"].apply(extract_post_info)
print("Flattened posts:", posts_flat.head())

Flattened posts:          id                                               text
0  0x61fc95  We got the ranch, loaded our guns and sat up t...
1  0x35663e  I bet there is an army of married couples who ...
2  0xc78afe                         This could only end badly.
3  0x90089c  My sister squeezed a lime in her milk when she...
4  0xaba820         and that got my head bobbing a little bit.

In [4]:
from google.colab import files
uploaded = files.upload()

Saving dm-lab-2-private-competition.zip to dm-lab-2-private-competition.zip

In [5]:
from google.colab import files
uploaded = files.upload()

Saving data_identification.csv to data_identification.csv
Saving emotion.csv to emotion.csv
Saving final_posts.json to final_posts.json
Saving samplesubmission.csv to samplesubmission.csv

In [14]:
import pandas as pd

# CSV files
id_df = pd.read_csv("data_identification.csv")
emotion_df = pd.read_csv("emotion.csv")


try:
    posts_df = pd.read_json("final_posts.json")
except ValueError:

    posts_df = pd.read_json("final_posts.json", lines=True)

print("ID columns:", id_df.columns)
print("Emotion columns:", emotion_df.columns)
print("Posts columns:", posts_df.columns)
posts_df.head()

ID columns: Index(['id', 'split'], dtype='object')
Emotion columns: Index(['id', 'emotion'], dtype='object')
Posts columns: Index(['root'], dtype='object')

                                                root
0  {'_type': 'post', '_source': {'post': {'post_i...
1  {'_type': 'post', '_source': {'post': {'post_i...
2  {'_type': 'post', '_source': {'post': {'post_i...
3  {'_type': 'post', '_source': {'post': {'post_i...
4  {'_type': 'post', '_source': {'post': {'post_i...

In [15]:
import pandas as pd

id_df = pd.read_csv("data_identification.csv")
emotion_df = pd.read_csv("emotion.csv")
posts_df = pd.read_json("final_posts.json")

print("ID columns:", id_df.columns)
print("Emotion columns:", emotion_df.columns)
print("Posts columns:", posts_df.columns)

example = posts_df["root"].iloc[0]
print("\nExample root dict:\n", example)
print("\nKeys in root:", example.keys())

if "_source" in example:
    print("Keys in _source:", example["_source"].keys())
    if "post" in example["_source"]:
        print("Keys in _source['post']:", example["_source"]["post"].keys())

ID columns: Index(['id', 'split'], dtype='object')
Emotion columns: Index(['id', 'emotion'], dtype='object')
Posts columns: Index(['root'], dtype='object')

Example root dict:
 {'_type': 'post', '_source': {'post': {'post_id': '0x61fc95', 'text': 'We got the ranch, loaded our guns and sat up till sunrise.', 'hashtags': []}}}

Keys in root: dict_keys(['_type', '_source'])
Keys in _source: dict_keys(['post'])
Keys in _source['post']: dict_keys(['post_id', 'text', 'hashtags'])

In [16]:
def extract_post_info(root_dict):

    d = root_dict
    src = d.get("_source", d)
    post = src.get("post", src)


    post_id = (
        post.get("id")
        or post.get("post_id")
        or post.get("tweet_id")
    )
    text = (
        post.get("text")
        or post.get("content")
        or post.get("body")
    )

    return pd.Series({"id": post_id, "text": text})

posts_flat = posts_df["root"].apply(extract_post_info)

print(posts_flat.head())

         id                                               text
0  0x61fc95  We got the ranch, loaded our guns and sat up t...
1  0x35663e  I bet there is an army of married couples who ...
2  0xc78afe                         This could only end badly.
3  0x90089c  My sister squeezed a lime in her milk when she...
4  0xaba820         and that got my head bobbing a little bit.

In [40]:
# Merge them
df_all = id_df.merge(posts_flat, on="id", how="left")

df_all = df_all.merge(emotion_df, on="id", how="left")

# Npw we can Split into train and test using the 'split' column
train_df = df_all[df_all["split"] == "train"].copy()
test_df  = df_all[df_all["split"] == "test"].copy()

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)
train_df.head()

Train shape: (47890, 4)
Test shape: (16281, 4)

         id  split                                               text emotion
1  0x35663e  train  I bet there is an army of married couples who ...     joy
2  0xc78afe  train                         This could only end badly.    fear
3  0x90089c  train  My sister squeezed a lime in her milk when she...     joy
7  0x2ffb63  train                                Thank you so much❤️     joy
9  0x989146  train  Stinks because ive been in this program for a ...     joy

In [22]:
X = train_df["text"]
y = train_df["emotion"]

In [44]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+|https\S+", " ", text)
    text = re.sub(r"@[A-Za-z0-9_]+", " ", text)
    text = re.sub(r"#", " ", text)
    text = re.sub(r"\d+", " ", text)
    text = text.translate(str.maketrans("", "", string.punctuation))
    text = re.sub(r"\s+", " ", text).strip()
    return text

train_df["text_clean"] = train_df["text"].apply(clean_text)
test_df["text_clean"]  = test_df["text"].apply(clean_text)

train_df[["text", "text_clean", "emotion"]].head()

,text,text_clean,emotion
1,I bet there is an army of married couples who ...,i bet there is an army of married couples who ...,joy
2,This could only end badly.,this could only end badly,fear
3,My sister squeezed a lime in her milk when she...,my sister squeezed a lime in her milk when she...,joy
7,Thank you so much❤️,thank you so much❤️,joy
9,Stinks because ive been in this program for a ...,stinks because ive been in this program for a ...,joy

In [24]:
X = train_df["text_clean"]
y = train_df["emotion"]

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

## 2. Feature Engineering Steps

In [33]:
### Add the code related to the feature engineering steps in cells inside this section
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    stop_words="english"
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_valid_tfidf = tfidf.transform(X_valid)

print("Train vectorized shape:", X_train_tfidf.shape)
print("Valid vectorized shape:", X_valid_tfidf.shape)

Train vectorized shape: (38312, 20000)
Valid vectorized shape: (9578, 20000)

In [30]:
model = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=20000,
        ngram_range=(1, 2),
        stop_words="english"
    )),
    ("clf", LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        n_jobs=-1
    ))
])

model.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=20000, ngram_range=(1, 2),
                                 stop_words='english')),
                ('clf',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    n_jobs=-1))])

In this first step, I cleaned and prepared the raw text data to remove noise and transform the tweets into a more standard and usable format. The preprocessing included the following operations:

*Lowercasing:
in this one, every tweet was converted to lowercase to maintain consistency.

*Removing URLs:
the hyperlinks such as http://..., https://..., or www... were removed because they do not provide emotional information.
*Removing Mentions and Hashtags:
the usernames (example: @user) were removed. Hashtags (example: #happy) had only the hash symbol removed, keeping the emotional word.

*Removing Numbers:
the digits were deleted since they typically do not reflect emotional content.

*Removing Punctuation:
in which punctuation marks were removed using Python’s string.punctuation tool.

*Removing Extra Spaces:
in which multiple spaces were collapsed into a single space for better formatting.

So we can see that the cleaned text was stored in a new variable called text_clean, which was used for all later steps including feature engineering and model training.

In [26]:
y_pred_valid = model.predict(X_valid)

print("Validation accuracy:", accuracy_score(y_valid, y_pred_valid))
print("\nClassification report:\n", classification_report(y_valid, y_pred_valid))
print("\nConfusion matrix:\n", confusion_matrix(y_valid, y_pred_valid))

Validation accuracy: 0.5279807893088327

Classification report:
               precision    recall  f1-score   support

       anger       0.51      0.50      0.50      2139
     disgust       0.13      0.27      0.18       237
        fear       0.29      0.53      0.37       402
         joy       0.82      0.59      0.68      4759
     sadness       0.31      0.41      0.35       785
    surprise       0.33      0.48      0.39      1256

    accuracy                           0.53      9578
   macro avg       0.40      0.46      0.41      9578
weighted avg       0.61      0.53      0.55      9578


Confusion matrix:
 [[1059  159  131  245  207  338]
 [  58   63   31   25   31   29]
 [  44   31  212   32   38   45]
 [ 558  140  216 2794  334  717]
 [ 138   39   61   98  321  128]
 [ 216   38   78  207  109  608]]

To convert the cleaned text into numerical features suitable for machine learning, I used the TF-IDF technique. It transforms each tweet into a vector based on the importance of its words.

Key decisions in feature engineering:

*TF-IDF Vectorizer:
is used to convert the text into numerical vectors based on frequency and importance.

*N-gram Range (1, 2):
Both unigrams and bigrams were included.

-Unigrams capture individual words (example: “happy”).

-Bigrams capture important expressions (example: “not happy”).

*Max Features : this part limited the vocabulary to the 20,000 most frequent n-grams to reduce noise and computation time.

*Stopword Removal:
common English words were removed to focus on emotional content.

Overall, we can say that the output of this step is a sparse TF-IDF matrix that encodes the importance of each word and phrase in the dataset.

## 3. Model Implementation Steps

In [34]:
### Add the code related to the model implementation steps in cells inside this section

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    n_jobs=-1
)


clf.fit(X_train_tfidf, y_train)

y_pred_valid = clf.predict(X_valid_tfidf)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Validation accuracy:", accuracy_score(y_valid, y_pred_valid))
print("\nClassification Report:\n", classification_report(y_valid, y_pred_valid))
print("\nConfusion Matrix:\n", confusion_matrix(y_valid, y_pred_valid))

Validation accuracy: 0.5279807893088327

Classification Report:
               precision    recall  f1-score   support

       anger       0.51      0.50      0.50      2139
     disgust       0.13      0.27      0.18       237
        fear       0.29      0.53      0.37       402
         joy       0.82      0.59      0.68      4759
     sadness       0.31      0.41      0.35       785
    surprise       0.33      0.48      0.39      1256

    accuracy                           0.53      9578
   macro avg       0.40      0.46      0.41      9578
weighted avg       0.61      0.53      0.55      9578


Confusion Matrix:
 [[1059  159  131  245  207  338]
 [  58   63   31   25   31   29]
 [  44   31  212   32   38   45]
 [ 558  140  216 2794  334  717]
 [ 138   39   61   98  321  128]
 [ 216   38   78  207  109  608]]

In [45]:

test_pred = model.predict(test_df["text_clean"])

submission = pd.DataFrame({
    "id": test_df["id"],
    "emotion": test_pred
})
submission.to_csv("submission.csv", index=False)

print("submission.csv has been saved!")
submission.head()

submission.csv has been saved!

         id   emotion
0  0x61fc95  surprise
4  0xaba820      fear
5  0x66e44d       joy
6  0xc03cf5       joy
8  0x02f65a      fear

In [27]:
model.fit(X, y)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=20000, ngram_range=(1, 2),
                                 stop_words='english')),
                ('clf',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    n_jobs=-1))])

In this stage, I trained a machine learning model to classify tweets into emotional categories based on the engineered features.

So, I used Logistic Regression, which is effective for text classification and handles high-dimensional sparse data well.

Key model settings:
*logistic Regression (we can also say Multiclass):it uses the one-vs-rest strategy to classify between multiple emotion categories.

*class_weight='balanced':
which automatically adjusts the model to handle class imbalance, ensuring minority emotions are also learned.

*max_iter=1000:
that ensures the algorithm has enough iterations to converge.

I trained the model on 80% of the training data and validated it on the remaining 20%. I evaluated performance using:

-Validation accuracy
-Precision, recall, and F1-score
-Confusion matrix to check class-specific errors

**Let's get our bonus step now**

So, to gain my additional point, and to also improve the model, I will show with you my extra experiments:
*First we have: Tried Different Models:
-Multinomial Naive Bayes: Fast but lower accuracy.

-Linear SVM: Good performance but slower.

*Second we have: Experimented with N-grams:

-Using only unigrams gave lower accuracy.

-Adding bigrams improved detection of expressions such as “not good”, “very sad”.

* Third we have: Class Imbalance Handling:
-Using class_weight='balanced' significantly improved recall for minority emotion classes.

*Fourth we have: Error Analysis:
In which the misclassifications often appeared in tweets that were ambiguous, sarcastic, extremely short, or contained mixed emotions.

*Last one we have: Insight:
A simple TF-IDF + Logistic Regression pipeline is strong for this competition.
We should also know that more complex models (example: BERT) could perform better, but were unnecessary to obtain a competitive ranking for this assignment.

Thank you for reading my bonus part.

In [5]:
import os

os.listdir()

['.config', 'sample_data']